### ISSUE TITLE
Track NLU checklist

### ISSUE THREAD

**Issue by umstek** [asymptote-inc/jury-web#11]
Rest of the features can be found [here](https://github.com/asymptote-inc/jury-server/issues/30).  

- App stages

  - [x] Instructions

  - [x] Terms of Service

  - [x] App restart  

  - [x] Rating interface

- Technical requirements 

  - [x] Developed for Android  

  - [x] Use without network connectivity  

  - [x] Reload capability 

- [x] User interface design

**Comment by umstek** [comment]
# App stages  

## Instructions  
- Help pages on how to **Install the app** and how to **Rate comments**.   
- _Intuitive_ design in simple rating mode  
- _Color_ and _emoji_ based design in advanced rating mode  

## Terms of service  
Displayed before signup, 3 conditions, in point form.  

## App restart  
Closing web browser/PWA and reopening causes an app restart.  
Last seen question and all already fetched questions, and answers that are not sent because of network issues, are preserved.  

## Rating interface  
- Both interfaces support skipping questions  
- And marking them as unreadable/not in English  
- Answers will be marked `readableAndInEnglish` automatically for other options  

### Simple intuitive interface  
- Rate toxicity only  
- One click submit  
- Descriptions in _simple English_  

### Advanced interface with all options  
- Toxicity  
- Profanity/Obscenity  
- Identity based hate  
- Insulting  
- Threatening  
- Additional comment (collapsible container)  
- More technical descriptions on hover  
- Impression with color and emoji  

# Technical requirements  

## Developed for android
React (CRA) based SPA (single page application) developed for any modern device with a web browser _including_ **Android**.  
Developed as a PWA (progressive web app) to support app installation on android devices and offline features.  

## Use without network connectivity  
Service worker enables caching and displaying web page without internet. If there is no network connection, answering for already loaded questions is still possible; answers will be saved and sent when network is available again and user tries to send a new answer. 
_Leaderboard, Sign Up and Login will not work when not connected, for reasons obvious._  
_Offline mode may not work on Apple devices._  

## Reload capability  
Logout and login again to reload new data properly. App updates will be downloaded on browser reload. Leaderboard will automatically refresh on load.  

# User interface design 
- User interface based on React   
- Semantic UI for React components and guidelines  
- Register with username/email/password  
- Login with username/password or email/password  
- Logout  
- Header (side)bar with navigation links  
- Simple rating view (see above)  
- Advanced rating view (see above)  
- Leaderboad with usernames and scores
